config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users

  root to: "homes#top"

  get "home/about"=>"homes#about", as: "about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => 'relationships#followings',as: "followings"
    get "followers" => 'relationships#followers',as: "followers"
  end

  get "search" => "searches#search",as: "search"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  before_action :authenticate_user!

  def search
    @range = params[:range]
    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @books = Book.looks(params[:search], params[:word])
    end
  end

end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_search.html.erb
<% if user_signed_in? %>
  <div class="search_form">
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['User'],['Book']]) %>
      <%= f.select :search, options_for_select([["完全一致","perfect_match"],["前方一致","forward_match"],["後方一致","backword_match"],["部分一致","partial_match"]]) %>
      <%= f.submit "検索" %>
    <% end %>
  </div>
<% end %>

app/views/searches/search.html.erb
<h2>Books search for "<%= @range %>"</h2>

<table class="col-lg-8 table table-border">
  <% if @range == "User" %>
    <% @users.each do |user| %>
      <tr>
        <th style="width:30%"></th>
        <th style="width:30%">name</th>
        <th style="width:30%">introduction</th>
      </tr>
      <tr>
        <td><%= image_tag user.get_profile_image, size: "50x50" %></td>
        <td><%= link_to "#{user.name}", user_path(user) %></td>
        <td><%= user.introduction %></td>
      </tr>
    <% end %>
  <% else %>
    <% @books.each do |book| %>
      <tr>
        <th style="width:30%"></th>
        <th style="width:30%">title</th>
        <th style="width:30%">body</th>
      </tr>
      <tr>
        <td><%= image_tag book.user.get_profile_image, size: '50x50' %></td>
        <td><%= link_to "#{book.title}", book_path(book) %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
  <% end %>
</table>